export function generateComplianceReportHTML(projectData, complianceResult) {
  const statusColor = complianceResult.status === 'pass' ? '#10b981' : '#ef4444';
  const statusText = complianceResult.status === 'pass' ? 'COMPLIANT' : 'NON-COMPLIANT';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    .header { text-align: center; border-bottom: 3px solid ${statusColor}; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: ${statusColor}; margin: 0; }
    .header p { color: #666; margin: 5px 0; }
    .section { margin: 30px 0; }
    .section h2 { color: #333; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin: 20px 0; }
    .info-item { padding: 10px; background: #f9fafb; border-radius: 5px; }
    .info-item strong { display: block; color: #666; font-size: 12px; margin-bottom: 5px; }
    .violation { background: #fee2e2; padding: 15px; margin: 10px 0; border-left: 4px solid #ef4444; border-radius: 5px; }
    .violation h4 { margin: 0 0 5px 0; color: #991b1b; }
    .recommendation { background: #fef3c7; padding: 15px; margin: 10px 0; border-left: 4px solid #f59e0b; border-radius: 5px; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #ddd; font-size: 12px; color: #666; }
    .disclaimer { background: #fff3cd; padding: 15px; border-radius: 5px; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>UDCPR COMPLIANCE REPORT</h1>
    <p>Status: <strong style="color: ${statusColor}">${statusText}</strong></p>
    <p>Generated on: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}</p>
  </div>

  <div class="section">
    <h2>Project Information</h2>
    <div class="info-grid">
      <div class="info-item">
        <strong>Project Name</strong>
        ${projectData.projectName || 'N/A'}
      </div>
      <div class="info-item">
        <strong>Location</strong>
        ${projectData.location || 'N/A'}
      </div>
      <div class="info-item">
        <strong>Zone Type</strong>
        ${projectData.zoneType || 'N/A'}
      </div>
      <div class="info-item">
        <strong>Plot Area</strong>
        ${projectData.plotArea || 'N/A'} sq.m
      </div>
      <div class="info-item">
        <strong>Proposed FSI</strong>
        ${projectData.proposedFSI || 'N/A'}
      </div>
      <div class="info-item">
        <strong>Permissible FSI</strong>
        ${projectData.permissibleFSI || 'N/A'}
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Compliance Summary</h2>
    <p>${complianceResult.summary}</p>
    <p><strong>Total Violations:</strong> ${complianceResult.violations.length}</p>
  </div>

  ${complianceResult.violations.length > 0 ? `
  <div class="section">
    <h2>Violations Found</h2>
    ${complianceResult.violations.map(v => `
      <div class="violation">
        <h4>${v.type}</h4>
        <p>${v.message}</p>
        <small>Severity: ${v.severity}</small>
      </div>
    `).join('')}
  </div>
  ` : ''}

  ${complianceResult.recommendations.length > 0 ? `
  <div class="section">
    <h2>Recommendations</h2>
    ${complianceResult.recommendations.map(r => `
      <div class="recommendation">
        <p>${r}</p>
      </div>
    `).join('')}
  </div>
  ` : ''}

  <div class="section">
    <h2>Applicable UDCPR Clauses</h2>
    <ul>
      <li>Chapter 3, Section 2 - FSI Regulations</li>
      <li>Chapter 3, Section 3 - Setback Requirements</li>
      <li>Chapter 5, Section 1 - Parking Requirements</li>
    </ul>
  </div>

  <div class="footer">
    <div class="disclaimer">
      <strong>DISCLAIMER:</strong> This report is generated by UDCPR Master, an independent reference and design tool. 
      It is not an official government document. For final approvals and legal compliance, please consult your local 
      planning authority and obtain necessary permissions as per UDCPR 2020 regulations.
    </div>
    <p style="text-align: center; margin-top: 20px;">
      Generated by UDCPR Master | www.udcprmaster.com
    </p>
  </div>
</body>
</html>
  `;
}

export async function generatePDFReport(projectData, complianceResult) {
  // For now, return HTML. In production, use puppeteer or similar to convert to PDF
  const html = generateComplianceReportHTML(projectData, complianceResult);
  return html;
}
